---
title: "Lipidomics BMP May 2023"
author: "Raghav Jain"
format: html
editor: visual
---

# 1. Load Packages

```{r}
#| echo: false
if(!require(tidyverse)){install.packages("tidyverse")}
if(!require(ggpubr)){install.packages("ggpubr")}
if(!require(RColorBrewer)){install.packages("RColorBrewer")}
if(!require(ggsci)){install.packages("ggsci")}
if(!require(scales)){install.packages("scales")}
if(!require(Cairo)){install.packages("Cairo")}
if(!require(rstatix)){install.packages("rstatix")}
if(!require(DataEditR)){install.packages("DataEditR")}
if(!require(ggbreak)){install.packages("ggbreak")}
if(!require(readxl)){install.packages("readxl")}
pal_45 <- c("#D51317", "#164194", "#F39200FF", "#31B7BCFF")
```

# 2. Exp 45

Exp 45 liver KD re-run

```{r}
# Load data
lipid_data <- read_csv("data/Targeted_BMP_May/2023_0512_Batch03_BMP_ng_mL.csv")
names(lipid_data) <- gsub(" Results", "", names(lipid_data))
names(lipid_data) <- gsub("-", "_", names(lipid_data))
lipid_data$ID <- as.character(lipid_data$ID)

# Load sample info
sample_info <- read_xlsx("data/Targeted_BMP_May/2023_0501 BMP run liver weights.xlsx")
names(sample_info)[1] <- "ID" 

# Merge columns
mdat <- merge(sample_info, lipid_data, by ="ID")

# Change 0 to NA, remove all NA columns
mdat[mdat == 0] <- NA
mdat <- mdat[,colSums(is.na(mdat))<nrow(mdat)]

# Final units in ng lipid/mg tissue
mdat[,12:ncol(mdat)] <- 0.150*mdat[,12:ncol(mdat)]/mdat$Weight_mg

# Create factors
mdat$Temp <- factor(mdat$Temp, levels = c("RT", "Cold"))
mdat$Condition <- paste0(mdat$Genotype, "_", mdat$Temp)
mdat$Condition <- factor(mdat$Condition, levels = c("Con_RT", "Con_Cold", 
                                                    "TFEB_KD_RT", "TFEB_KD_Cold")
                         )

# Calculate total lipid class sums
mdat$Total_BMP <- rowSums(mdat[, grepl("BMP", names(mdat))])
mdat$Total_PG <- rowSums(mdat[, grepl("PG", names(mdat))])

# Reorder columns
mdat <- mdat |> select(Exp_ID, Experiment, ID, 
                       Condition, Temp:Batch,
                       `BMP 16:0_16:0`:Total_PG
                       )
write_csv(mdat, "data/Targeted_BMP_May/ng_mg/2023_0515_Exp45_Targeted_BMP_liver_redo.csv")
```

## Total BMP/PG

```{r}
mdat <- read_csv("data/Targeted_BMP_May/ng_mg/2023_0515_Exp45_Targeted_BMP_liver_redo.csv")
p0 <- ggbarplot(mdat, x = "Condition", y = "Total_BMP",
                add = c("mean_sd", "dotplot"),
                color = "Condition", fill = "Condition", 
                error.plot = "errorbar", 
                add.params = list(width = 0.25,
                                  binwidth = .020*max(mdat$Total_BMP, 
                                                      na.rm = T)
                                  ),
                position = position_dodge(0.8),
                size = 0.15) +
  scale_y_continuous(limits = c(0.00, 1.75*max(mdat$Total_BMP, na.rm = T)
                                ),
                     expand = c(0,0)
                     )

p1 <- ggpar(p0, palette = pal_45, legend = "right", 
            legend.title = "Condition", 
            title = "Total BMP",  
            xlab = "Condition", 
            ylab = "ng lipid/mg tissue")

stat.test <- mdat |>
  na.omit() |>
  t_test(Total_BMP ~ Condition) |>
  adjust_pvalue(method = "none") |>
  add_significance("p")

stat.test$p.adj.signif <- stat.test$p.signif
stat.test <- stat.test |>
  add_xy_position(fun = "max", dodge = 0.8) 

p2 <- p1 + stat_pvalue_manual(
  stat.test, label = "p", 
  size = 4,
  step.increase = 0.12,
  bracket.nudge.y = 0,
  tip.length = 0.02, hide.ns = F)

p3 <- p2 +
  theme_bw(base_size = 16, base_family = "Arial") +
  scale_color_manual(values = c("black", "black",
                                "black", "black")
                     )

CairoPDF(file = "output/Fig4/Fig4D_Exp45_total_BMP_rerun.pdf", height = 10, width = 12)
  print(p3)
dev.off()
```

# 3. Exp 51 and 26

Old Male (Exp26) and young Female (Exp51) RT v Cold

```{r}
lipid_data <- read_csv("data/Targeted_BMP_May/2023_0511_Batch01_BMP_ng_mL.csv")
names(lipid_data) <- gsub(" Results", "", names(lipid_data))
names(lipid_data) <- gsub("-", "_", names(lipid_data))
lipid_data$ID <- as.character(lipid_data$ID)

# Load sample info
sample_info <- read_xlsx("data/Targeted_BMP_May/2023_0501 BMP run liver weights.xlsx")
names(sample_info)[1] <- "ID" 

# Merge columns
mdat <- merge(sample_info, lipid_data, by ="ID")

# Change 0 to NA, remove all NA columns
mdat[mdat == 0] <- NA
mdat <- mdat[,colSums(is.na(mdat))<nrow(mdat)]

# Final units in ng lipid/mg tissue
mdat[,13:ncol(mdat)] <- 0.150*mdat[,13:ncol(mdat)]/mdat$Weight_mg

# Create factor(s)
mdat$Temp <- factor(mdat$Temp, levels = c("RT", "Cold"))

# Calculate total lipid class sums
mdat$Total_BMP <- rowSums(mdat[, grepl("BMP", names(mdat))], na.rm = T)
mdat$Total_PG <- rowSums(mdat[, grepl("PG", names(mdat))], na.rm = T)

# Reorder columns
mdat <- mdat |> select(Exp_ID, Experiment, ID, 
                       Temp:Batch,
                       `BMP 16:0_16:0`:Total_PG
                       )

mdat1 <- mdat |> filter(Experiment == 26)
mdat2 <- mdat |> filter(Experiment == 51)

write_csv(mdat1, "data/Targeted_BMP_May/ng_mg/2023_0515_Exp26_Targeted_BMP_liver_old_male.csv")
write_csv(mdat2, "data/Targeted_BMP_May/ng_mg/2023_0515_Exp51_Targeted_BMP_liver_female.csv")
```

## Exp 26 Total BMP

```{r}
mdat <- read_csv("data/Targeted_BMP_May/ng_mg/2023_0515_Exp26_Targeted_BMP_liver_old_male.csv")

mdat$Temp <- factor(mdat$Temp, levels = c("RT", "Cold"))

p0 <- ggbarplot(mdat, x = "Temp", y = "Total_BMP",
                add = c("mean_sd", "dotplot"),
                color = "Temp", fill = "Temp", 
                error.plot = "errorbar", 
                add.params = list(width = 0.25,
                                  binwidth = .020*max(mdat$Total_BMP, 
                                                      na.rm = T)
                                  ),
                position = position_dodge(0.8),
                size = 0.15) +
  scale_y_continuous(limits = c(0.00, 1.75*max(mdat$Total_BMP, na.rm = T)
                                ),
                     expand = c(0,0)
                     )

p1 <- ggpar(p0, palette = pal_45, legend = "right", 
            legend.title = "Condition", 
            title = "Total BMP",  
            xlab = "Condition", 
            ylab = "ng lipid/mg tissue")

stat.test <- mdat |>
  na.omit() |>
  t_test(Total_BMP ~ Temp) |>
  adjust_pvalue(method = "none") |>
  add_significance("p")

stat.test$p.adj.signif <- stat.test$p.signif
stat.test <- stat.test |>
  add_xy_position(fun = "max", dodge = 0.8) 

p2 <- p1 + stat_pvalue_manual(
  stat.test, label = "p", 
  size = 4,
  step.increase = 0.12,
  bracket.nudge.y = 0,
  tip.length = 0.02, hide.ns = F)

p3 <- p2 +
  theme_bw(base_size = 16, base_family = "Arial") +
  scale_color_manual(values = c("black", "black")
                     )

CairoPDF(file = "output/Misc/Exp26_total_BMP_old_male.pdf", height = 10, width = 12)
  print(p3)
dev.off()
```

## Exp 26 BMP species

```{r}
mdat2 <- mdat |> select(ID:Sex,
                        `BMP 16:0_16:0`:`BMP 22:6_22:6`)
mdat3 <- mdat2 |> pivot_longer(-c(ID, Temp, Sex), 
                               names_to = "Lipid",
                               values_to = "value")

mdat3$Lipid <- gsub("BMP ", "", mdat3$Lipid)

stat.test <- mdat3 |>
  group_by(Lipid) |>
  t_test(value ~ Temp) |>
  adjust_pvalue(method = "none") |>
  add_significance("p")

old_sig <- stat.test[stat.test$p < 0.05,]$Lipid

mdat4 <- mdat3 |> filter(Lipid %in% old_sig)

p0 <- ggbarplot(mdat4, x = "Lipid", y = "value",
                add = c("mean_sd", "dotplot"), 
                color = "Temp", fill = "Temp", 
                error.plot = "errorbar", 
                add.params = list(width = 0.20,
                                  binwidth = .015*max(mdat4$value, 
                                                      na.rm = T)
                                  ),
                position = position_dodge(0.8), size = 0.15) +
  scale_y_continuous(limits = c(0.00, 2.0*max(mdat4$value, na.rm = T)
                                ),
                     expand = c(0,0)
                     ) 
p1 <- ggpar(p0, palette = pal_45, legend = "top",
            legend.title = "Condition", 
            title = "Liver BMP lipid species",
            xlab = "Lipid",
            ylab = "ng lipid/mg tissue") +
  theme_bw(base_size = 16, base_family = "Arial") +
  theme(text = element_text(face = "bold", 
                            colour = "black")
        ) +
  scale_color_manual(values = c("black", "black", 
                                "black", "black")
                     )

stat.test <- mdat4 |>
  group_by(Lipid) |>
  t_test(value ~ Temp) |>
  adjust_pvalue(method = "none") |>
  add_significance("p")

stat.test$p.adj.signif <- stat.test$p.signif
stat.test <- stat.test |>
  na.omit() |>
  add_xy_position(fun = "max", "Lipid", dodge = 0.8) 

p2 <- p1 + stat_pvalue_manual(label = "p.signif",
                              size = 4,
                              vjust = 0,
                              bracket.nudge.y = 0,
                              stat.test, 
                              tip.length = 0.02, 
                              hide.ns = T)
p2
```

## Exp 51 Total BMP

```{r}
mdat <- read_csv("data/Targeted_BMP_May/ng_mg/2023_0515_Exp51_Targeted_BMP_liver_female.csv")

mdat$Temp <- factor(mdat$Temp, levels = c("RT", "Cold"))

p0 <- ggbarplot(mdat, x = "Temp", y = "Total_BMP",
                add = c("mean_sd", "dotplot"),
                color = "Temp", fill = "Temp", 
                error.plot = "errorbar", 
                add.params = list(width = 0.25,
                                  binwidth = .020*max(mdat$Total_BMP, 
                                                      na.rm = T)
                                  ),
                position = position_dodge(0.8),
                size = 0.15) +
  scale_y_continuous(limits = c(0.00, 1.75*max(mdat$Total_BMP, na.rm = T)
                                ),
                     expand = c(0,0)
                     )

p1 <- ggpar(p0, palette = pal_45, legend = "right", 
            legend.title = "Condition", 
            title = "Total BMP",  
            xlab = "Condition", 
            ylab = "ng lipid/mg tissue")

stat.test <- mdat |>
  na.omit() |>
  t_test(Total_BMP ~ Temp) |>
  adjust_pvalue(method = "none") |>
  add_significance("p")

stat.test$p.adj.signif <- stat.test$p.signif
stat.test <- stat.test |>
  add_xy_position(fun = "max", dodge = 0.8) 

p2 <- p1 + stat_pvalue_manual(
  stat.test, label = "p", 
  size = 4,
  step.increase = 0.12,
  bracket.nudge.y = 0,
  tip.length = 0.02, hide.ns = F)

p3 <- p2 +
  theme_bw(base_size = 16, base_family = "Arial") +
  scale_color_manual(values = c("black", "black")
                     )

CairoPDF(file = "output/Misc/Exp51_total_BMP_young_female.pdf", height = 10, width = 12)
  print(p3)
dev.off()
```

# 4. Exp 47

Youn Male and young Female mice RT v Cold

```{r}
lipid_data <- read_csv("data/Targeted_BMP_May/2023_0511_Batch02_BMP_ng_mL.csv")
names(lipid_data) <- gsub(" Results", "", names(lipid_data))
names(lipid_data) <- gsub("-", "_", names(lipid_data))
lipid_data$ID <- as.character(lipid_data$ID)

# Load sample info
sample_info <- read_xlsx("data/Targeted_BMP_May/2023_0501 BMP run liver weights.xlsx")
names(sample_info)[1] <- "ID" 

# Merge columns
mdat <- merge(sample_info, lipid_data, by ="ID")

# Change 0 to NA, remove all NA columns
mdat[mdat == 0] <- NA
mdat <- mdat[,colSums(is.na(mdat))<nrow(mdat)]

# Final units in ng lipid/mg tissue
mdat[,12:ncol(mdat)] <- 0.150*mdat[,12:ncol(mdat)]/mdat$Weight_mg

# Create factor(s)
mdat$Temp <- factor(mdat$Temp, levels = c("RT", "Cold"))

# Calculate total lipid class sums
mdat$Total_BMP <- rowSums(mdat[, grepl("BMP", names(mdat))], na.rm = T)
mdat$Total_PG <- rowSums(mdat[, grepl("PG", names(mdat))], na.rm = T)

# Reorder columns
mdat <- mdat |> select(Exp_ID, Experiment, ID, 
                       Temp:Batch,
                       `BMP 16:0_16:0`:Total_PG
                       )

write_csv(mdat, "data/Targeted_BMP_May/ng_mg/2023_0515_Exp47_Targeted_BMP_liver_male_female.csv")
```

## Total BMP

```{r}
mdat <- read_csv("data/Targeted_BMP_May/ng_mg/2023_0515_Exp47_Targeted_BMP_liver_male_female.csv")

mdat$Condition <- paste0(mdat$Sex, "_", mdat$Temp)
mdat$Condition <- factor(mdat$Condition, levels = c("Female_RT", "Female_Cold",
                                                    "Male_RT", "Male_Cold"))

p0 <- ggbarplot(mdat, x = "Condition", y = "Total_BMP",
                add = c("mean_sd", "dotplot"),
                color = "Condition", fill = "Condition", 
                error.plot = "errorbar", 
                add.params = list(width = 0.25,
                                  binwidth = .020*max(mdat$Total_BMP, 
                                                      na.rm = T)
                                  ),
                position = position_dodge(0.8),
                size = 0.15) +
  scale_y_continuous(limits = c(0.00, 1.75*max(mdat$Total_BMP, na.rm = T)
                                ),
                     expand = c(0,0)
                     )

p1 <- ggpar(p0, palette = pal_45, legend = "right", 
            legend.title = "Condition", 
            title = "Total BMP",  
            xlab = "Condition", 
            ylab = "ng lipid/mg tissue")

stat.test <- mdat |>
  t_test(Total_BMP ~ Condition) |>
  adjust_pvalue(method = "none") |>
  add_significance("p")

stat.test$p.adj.signif <- stat.test$p.signif
stat.test <- stat.test |>
  add_xy_position(fun = "max", dodge = 0.8) 

p2 <- p1 + stat_pvalue_manual(
  stat.test, label = "p", 
  size = 4,
  step.increase = 0.12,
  bracket.nudge.y = 0,
  tip.length = 0.02, hide.ns = F)

p3 <- p2 +
  theme_bw(base_size = 16, base_family = "Arial") +
  scale_color_manual(values = c("black", "black", "black", "black")
                     )

CairoPDF(file = "output/Misc/Exp47_total_BMP_young_male_female.pdf", height = 10, width = 12)
  print(p3)
dev.off()
```

## BMP Species

```{r}
mdat2 <- mdat |> select(ID:Sex, Condition, 
                        `BMP 16:0_16:0`:`BMP 22:6_22:6`)
mdat3 <- mdat2 |> pivot_longer(-c(ID, Temp, Sex, Condition), 
                               names_to = "Lipid",
                               values_to = "value")

mdat3$Lipid <- gsub("BMP ", "", mdat3$Lipid)

mdat4 <- mdat3 |> filter(Sex == "Male")

stat.test <- mdat4 |>
  group_by(Lipid) |>
  t_test(value ~ Temp) |>
  adjust_pvalue(method = "none") |>
  add_significance("p")

male_sig <- stat.test[stat.test$p < 0.05,]$Lipid

mdat5 <- mdat3 |> filter(Sex == "Female")

stat.test <- mdat5 |>
  group_by(Lipid) |>
  t_test(value ~ Temp) |>
  adjust_pvalue(method = "none") |>
  add_significance("p")

female_sig <- stat.test[stat.test$p < 0.05,]$Lipid

BMP_unique <- male_sig[!male_sig %in% female_sig]
Both <- male_sig[male_sig %in% female_sig]

# High all
all_high <- c("18:1_18:2", "18:1_18:1",
              "18:1_22:6", "18:1_20:4",
              "18:2_18:2", "18:2_20:4")

# From old mouse data

mdat4 <- mdat3 |> filter(Lipid %in% old_sig)

p0 <- ggbarplot(mdat4, x = "Lipid", y = "value",
                add = c("mean_sd", "dotplot"), 
                color = "Condition", fill = "Condition", 
                error.plot = "errorbar", 
                add.params = list(width = 0.20,
                                  binwidth = .015*max(mdat4$value, 
                                                      na.rm = T)
                                  ),
                position = position_dodge(0.8), size = 0.15) +
  scale_y_continuous(limits = c(0.00, 2.0*max(mdat4$value, na.rm = T)
                                ),
                     expand = c(0,0)
                     ) 
p1 <- ggpar(p0, palette = pal_45, legend = "top",
            legend.title = "Condition", 
            title = "Liver BMP lipid species",
            xlab = "Lipid",
            ylab = "ng lipid/mg tissue") +
  theme_bw(base_size = 16, base_family = "Arial") +
  theme(text = element_text(face = "bold", 
                            colour = "black"),
        axis.text.x = element_text(angle = 90, hjust = 1)
        ) +
  scale_color_manual(values = c("black", "black", 
                                "black", "black")
                     ) 
stat.test <- mdat4 |>
  group_by(Lipid) |>
  t_test(value ~ Condition) |>
  adjust_pvalue(method = "none") |>
  add_significance("p")

stat.test$p.adj.signif <- stat.test$p.signif
stat.test <- stat.test |>
  na.omit() |>
  add_xy_position(fun = "max", "Lipid", dodge = 0.8) 

p2 <- p1 + stat_pvalue_manual(label = "p.signif",
                              size = 4,
                              vjust = 0.0,
                              bracket.nudge.y = 0.0,
                              stat.test, 
                              tip.length = 0.02, 
                              hide.ns = T)
p2
```

# 5. Primary Hepatocytes

BCA was with 200uL RIPA to pellets. Exp34

```{r}
lipid_data <- read_csv("data/Targeted_BMP_May/2023_0510_PrimaryHep_BMP_ng_mL.csv")
names(lipid_data) <- gsub(" Results", "", names(lipid_data))
names(lipid_data) <- gsub("-", "_", names(lipid_data))


# Load sample info
sample_info <- read_xlsx("data/Targeted_BMP_May/2022_0708_lipidomics_primary_hep_bca.xlsx", sheet = "Protein")
names(sample_info)[1] <- "ID" 

# Merge columns
mdat <- merge(sample_info, lipid_data, by ="ID")

# Change 0 to NA, remove all NA columns
mdat[mdat == 0] <- NA
mdat <- mdat[,colSums(is.na(mdat))<nrow(mdat)]

# Final units in ng lipid/mg protein
mdat[,5:ncol(mdat)] <- 0.150*mdat[,5:ncol(mdat)]/(mdat$`Conc (ug/uL)`*0.2)

# Create factor(s)
mdat$Temp <- factor(mdat$Temp, levels = c("RT", "Cold"))

# Calculate total lipid class sums
mdat$Total_BMP <- rowSums(mdat[, grepl("BMP", names(mdat))], na.rm = T)
mdat$Total_PG <- rowSums(mdat[, grepl("PG", names(mdat))], na.rm = T)

# Reorder columns
mdat <- mdat |> select(ID:Temp,
                       `BMP 16:0_16:0`:Total_PG
                       )

write_csv(mdat, "data/Targeted_BMP_May/ng_mg/2023_0515_PrimaryHepa_Targeted_BMP_male.csv")
```

## Total BMP

```{r}
mdat <- read_csv("data/Targeted_BMP_May/ng_mg/2023_0515_PrimaryHepa_Targeted_BMP_male.csv")

mdat$Temp <- factor(mdat$Temp, levels = c("RT", "Cold"))

p0 <- ggbarplot(mdat, x = "Temp", y = "Total_BMP",
                add = c("mean_sd", "dotplot"),
                color = "Temp", fill = "Temp", 
                error.plot = "errorbar", 
                add.params = list(width = 0.25,
                                  binwidth = .020*max(mdat$Total_BMP, 
                                                      na.rm = T)
                                  ),
                position = position_dodge(0.8),
                size = 0.15) +
  scale_y_continuous(limits = c(0.00, 1.75*max(mdat$Total_BMP, na.rm = T)
                                ),
                     expand = c(0,0)
                     )

p1 <- ggpar(p0, palette = pal_45, legend = "right", 
            legend.title = "Condition", 
            title = "Total BMP",  
            xlab = "Condition", 
            ylab = "ng lipid/mg tissue")

stat.test <- mdat |>
  na.omit() |>
  t_test(Total_BMP ~ Temp) |>
  adjust_pvalue(method = "none") |>
  add_significance("p")

stat.test$p.adj.signif <- stat.test$p.signif
stat.test <- stat.test |>
  add_xy_position(fun = "max", dodge = 0.8) 

p2 <- p1 + stat_pvalue_manual(
  stat.test, label = "p", 
  size = 4,
  step.increase = 0.12,
  bracket.nudge.y = 0,
  tip.length = 0.02, hide.ns = F)

p3 <- p2 +
  theme_bw(base_size = 16, base_family = "Arial") +
  scale_color_manual(values = c("black", "black")
                     )

CairoPDF(file = "output/Misc/Primary_Hep.pdf", height = 10, width = 12)
  print(p3)
dev.off()
```

# 6. Hepa1-6 Redos

Various siRNA KD lines. Initially ran all this in January. BCA in 100uL RIPA

```{r}
lipid_data <- read_csv("data/Targeted_BMP_May/2023_0512_Hepa_redo_BMP_ng_mL.csv")
names(lipid_data) <- gsub(" Results", "", names(lipid_data))
names(lipid_data) <- gsub("-", "_", names(lipid_data))

# Load sample info
sample_info <- read_xlsx("data/Targeted_BMP_May/2023_0119_Hepa_BMP.xlsx")
names(sample_info)[1] <- "ID" 

# Merge columns
mdat <- merge(sample_info, lipid_data, by ="ID")

# Change 0 to NA, remove all NA columns
mdat[mdat == 0] <- NA
mdat <- mdat[,colSums(is.na(mdat))<nrow(mdat)]

# Final units in ng lipid/mg protein
mdat[,5:ncol(mdat)] <- 0.140*mdat[,5:ncol(mdat)]/(mdat$`conc (ug/mL)`*0.1)

# Calculate total lipid class sums
mdat$Total_BMP <- rowSums(mdat[, grepl("BMP", names(mdat))], na.rm = T)
mdat$Total_PG <- rowSums(mdat[, grepl("PG", names(mdat))], na.rm = T)

# Reorder columns
mdat <- mdat |> select(ID, `Cell line`,
                       `BMP 16:0_16:0`:Total_PG
                       )
# Remove these lipids
mdat <- mdat |> select(-c(`BMP 16:0_18:3`, `BMP 18:2_18:3`, `BMP 18:2_22:5`, `BMP 18:3_22:5`,
                          `BMP 22:6_22:6`, `PG 16:0_18:3`, `PG 16:1_20:5`, `PG 16:1_22:6`,
                          `PG 18:0_20:5`, `PG 18:1_18:2`, `PG 18:1_18:3`, `PG 18:2_18:2`,
                          `PG 18:2_18:3`, `PG 18:2_20:4`, `PG 18:2_20:5`, `PG 20:4_20:4`,
                          `PG 20:4_20:5`, `PG 20:5_20:5`, `PG 22:6_22:6`)
                       )

write_csv(mdat, "data/Targeted_BMP_May/ng_mg/2023_0515_Hepa1_6_Targeted_BMP_rerun.csv")
```

## Total BMP

```{r}
mdat <- read_csv("data/Targeted_BMP_May/ng_mg/2023_0515_Hepa1_6_Targeted_BMP_rerun.csv")

mdat$`Cell line` <- factor(mdat$`Cell line`, levels = c("LacZ", "hAlg12",
                                                        "scramble_1", "siTFEB_siM6PR",
                                                        "scramble_2", "siPla2g15"))

names(mdat)[2] <- "Cell_line"

p0 <- ggbarplot(mdat, x = "Cell_line", y = "Total_BMP",
                add = c("mean_sd", "dotplot"),
                color = "Cell_line", fill = "Cell_line", 
                error.plot = "errorbar", 
                add.params = list(width = 0.25,
                                  binwidth = .020*max(mdat$Total_BMP, 
                                                      na.rm = T)
                                  ),
                position = position_dodge(0.8),
                size = 0.15) +
  scale_y_continuous(limits = c(0.00, 1.75*max(mdat$Total_BMP, na.rm = T)
                                ),
                     expand = c(0,0)
                     )

p1 <- ggpar(p0, palette = "pal_aaas", legend = "right", 
            legend.title = "Condition", 
            title = "Total BMP",  
            xlab = "Cell Line", 
            ylab = "ng lipid/mg protein")

stat.test <- mdat |>
  t_test(Total_BMP ~ Cell_line) |>
  adjust_pvalue(method = "none") |>
  add_significance("p")

stat.test$p.adj.signif <- stat.test$p.signif
stat.test <- stat.test |>
  add_xy_position(fun = "max", dodge = 0.8) 

p2 <- p1 + stat_pvalue_manual(
  stat.test, label = "p", 
  size = 4,
  step.increase = 0.12,
  bracket.nudge.y = 0,
  tip.length = 0.02, hide.ns = T)

p3 <- p2 +
  theme_bw(base_size = 16, base_family = "Arial") +
  scale_color_manual(values = c("black", "black", "black", "black", "black", "black")
                     )

CairoPDF(file = "output/Misc/Hepa_redo.pdf", height = 10, width = 12)
  print(p3)
dev.off()
```
